### ISSUE TITLE
First index of an element in array using recursion 

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#104]
---
Title: First index  of an element in array.
About: I would like to add solution to this problem.
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like...**
I would like to add solution to this problem.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will be adding this in array folder by making a new folder named all indices of array and initializing with a readme.

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned. @siddhi-244

**Comment by prathimacode-hub** [comment]
Its been 12 days and no PR from you yet. @siddhi-244

**Comment by siddhi-244** [comment]
I am srry I was not well. Will do  it today.

**Comment by siddhi-244** [comment]
> Its been 12 days and no PR from you yet. @siddhi-244

@prathimacode-hub
