### ISSUE TITLE
Vignere Cipher

### ISSUE THREAD

**Issue by DurgaSai-16** [prathimacode-hub/PyAlgo-Tree#106]
| Title|About |Name |Label |
|-|-|-|-|
| Vignere Cipher| Algorithm of encrypting an alphabetic text that uses a series of interwoven caesar ciphers | [Nallani Durga Sai](https://github.com/DurgaSai-16) | Feature Request|

**Define You:**    
- [X] DevIncept Participant

**Description:**
- Vignere Cipher is one of the secure encryption modes.
- Want to code a program that helps us to implement Vignere Ciphere for any given message text by using  key as of our choice.  
Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned. @DurgaSai-16
