### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by neha030** [prathimacode-hub/PyAlgo-Tree#11]
Title: Binary Search Tree in python
Name: NEHA JHA
Label: Feature Request
Assignee: ''

**Define You:**

✅ DevIncept Participant
 Contributor

**Is your feature request related to a problem? Please describe.**
Its a new feature.

**Describe the solution you'd like...**
IMPLEMENTATION OF BINARY SEARCH TREE (BST)
    Binary Search Tree is a special type of binary tree where:
    1. The value of all the nodes in the left sub-tree is less than or equal to the value of the root.
    2. The value of all the nodes in the right sub-tree is greater than value of the root.
    3. This rule will be recursively applied to all the left and right sub-trees of the root.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

This program contains the menu-based implementation of the basic operations on a BST:
    1. Insert Node into BST
    2. Search Node in BST
    3. Delete Node in BST
    4. Print BST (inorder way)

**Comment by prathimacode-hub** [comment]
Issue assigned. You can proceed. @neha030
