### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by neha030** [prathimacode-hub/PyAlgo-Tree#110]
**Title**: Quick Sort.
**About**: I would like to add solution to this problem.
**Name**: NEHA JHA
**Label**: Feature Request

✅ DevIncept Participant
 Contributor

**Is your feature request related to a problem? Please describe.**
  No

**Describe the solution you'd like...**
In this algorithm firstly it picks a pivot element and arranges the array according to this pivot element. The condition to arrange the array according to pivot element is that all the elements which are smaller than or equal to pivot must lie on the left side of the pivot. And all the elements which are greater than the pivot must lie on the right side of the pivot. After that follow the same approach on the left part of the pivot and right part of the pivot respectively until we left with a single element and finally we got our array sorted.

**Describe alternatives you've considered?**
None

**Approach to be followed (optional):**
I will add a folder name Quick Sort and all the files inside that with a README  file.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neha030
