### ISSUE TITLE
Circular linked list traversal

### ISSUE THREAD

**Issue by vishvarana** [prathimacode-hub/PyAlgo-Tree#112]
Project Title - Circular linked list traversal using python
YourName - Vishva Rana
Feature Request - Inserting the elements in cll and traversal

 ✅DevIncept Participant
✅ Contributor
Is your feature request related to a problem? Please describe.
Problem is related to the title given

Describe the solution you'd like...
Pushing the nodes in cll and their traversal

Describe alternatives you've considered?
I am also thinking of adding deletion and adding node at end or at a particular position features

**Comment by prathimacode-hub** [comment]
Issue assigned. @vishvarana

**Comment by prathimacode-hub** [comment]
Its been 11days and no PR from you yet. @vishvarana

**Comment by vishvarana** [comment]
Was working on a different issue but will complete it in coming 3 days for sure.
