### ISSUE TITLE
Face Recognition 

### ISSUE THREAD

**Issue by SANJAY-NT** [prathimacode-hub/PyAlgo-Tree#115]
---
Title: Face Recognition
About: A computer vision application face recognition.
Name:  Sanjay N T
Label: New Feature 
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
- Yes its a application of computer vision, to recognize the face of a person in front of the input camera.

**Describe the solution you'd like...**
- My approach is to use openCV module and built in methods, to train the model and using camera input to recognize the person in front of the camera at that time .

**Describe alternatives you've considered?**
- Instead of image as input we can use video as input and work on it.

**Approach to be followed (optional):**

**Additional context**
- This will be a great opportunity for me to learn and start working on the new technology.

**Comment by prathimacode-hub** [comment]
Issue assigned. @SANJAY-NT

**Comment by prathimacode-hub** [comment]
I had assigned issue, but do the requested changes of your earlier PR before you work on this. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
Yes, I shall update soon.

**Comment by prathimacode-hub** [comment]
Its been 10days and no PR form you yet. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
Yes, Mam I am doing it I shall update in 2 to 3 days.

**Comment by prathimacode-hub** [comment]
Ok, sure. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
I was still updating read me. Its not correct I shall update it today.

**Comment by prathimacode-hub** [comment]
> I was still updating read me. Its not correct I shall update it today.

I know its not correct, but still its been merged. @SANJAY-NT
