### ISSUE TITLE
Queue based on Linked List

### ISSUE THREAD

**Issue by nknantha** [prathimacode-hub/PyAlgo-Tree#116]
---
Title: Queue based on Linked List
Name: NanthaKumar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No. It's a new feature.

**Describe the solution you'd like...**

A Queue implemented by linked list from scratch. It will contains methods like enqueue(), dequeue(), peek() and etc.
By implementing with linked list, it'll give enqueue() and dequeue() operations in O(1) time.

**Comment by prathimacode-hub** [comment]
You can proceed. Issue assigned. @nknantha
