### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by neha030** [prathimacode-hub/PyAlgo-Tree#118]
Title: Shell Sort.
About: I would like to add solution to this problem.
Name: NEHA JHA
Label: Feature Request

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
No

Describe the solution you'd like...
Shell sort is a highly efficient sorting algorithm and is based on insertion sort algorithm. Shell sort is the generalization of insertion sort which overcomes the drawbacks of insertion sort by comparing elements separated by a gap of several positions.

Shell sort divides the array in the form of N/2 , N/4 , …, 1 (where N is the length of array) and then sorting is done. This breaking of sequence and sorting takes place until the entire array is sorted.

Describe alternatives you've considered?
None

Approach to be followed (optional):
I will add a folder name Shell Sort and all the files inside that with a README file.

**Comment by prathimacode-hub** [comment]
Issue assigned. @neha030
