### ISSUE TITLE
Bitwise AND

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#120]
---
Title: Bitwise AND
About: Given set S = {1,2,3,....,N}. The aim is to find two integers, I and J (where I<J), from set S such that the value of I & J is the maximum possible and also less than a given integer, K. In this case, '&' represents the bitwise AND operator.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The main purpose is to explore bitwise AND operator in python.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
