### ISSUE TITLE
BST Level Order Traversal

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#123]
---
Title: BST Level Order Traversal
About: The aim is to perform level-order traversal on a BST.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The purpose is to explore linked lists and tree traversals in python.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
