### ISSUE TITLE
Capitalizing

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#126]
---
Title: Capitalizing
About: The aim is to replace the first character of all the words with their upper case characters.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The purpose is to explore string functions like slicing.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
