### ISSUE TITLE
Diffie Hellmann Algorithm

### ISSUE THREAD

**Issue by dilroseR** [prathimacode-hub/PyAlgo-Tree#128]
**Title:** Diffie-Hellman Key Exchange

**About:**  Diffie-Hellman Key Exchange to ensure sender & receiver can only communicate if they have share same secret key

**Name:** Dilrose Reji

**Label:** Feature Request
Assignee: ''

**Define You:**
- [x] DevIncept Participant
- [x] Contributor

### Is your feature request related to a problem? Please describe.

Diffie-Hellman Key exchange algorithm will check if the sender & receiver has the same shared key, if not they can communicate

### Describe the solution you'd like...
Will be implementing it based on the algorithm in python

Kindly assign this to me

**Comment by prathimacode-hub** [comment]
Issue assigned. Kindly address the changes to your earlier PR before you create this PR. @dilroseR
