### ISSUE TITLE
Affine Cipher

### ISSUE THREAD

**Issue by manvitha3579** [prathimacode-hub/PyAlgo-Tree#129]
---
|Title| About| Name| Label|
|-|-|-|-|
|Affine Cipher| The affine cipher is a type of monoalphabetic substitution cipher| [Manvitha Chowdary Ramineni](https://github.com/manvitha3579)| Feature Request|
- - -
**Define You:**
- [x] DevIncept Participant

**Description:**
- Affine cipher,is an example of a substitution cipher
- In encryption using a substitution cipher, each time a given letter occurs in the plaintext, it always is replaced by the same ciphertext letter.

**Please assign this issue to me** @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned. @manvitha3579

**Comment by prathimacode-hub** [comment]
Its been 5days and no update from you yet or PR. @manvitha3579
