### ISSUE TITLE
Graph-BST

### ISSUE THREAD

**Issue by Apekshamarutip1** [prathimacode-hub/PyAlgo-Tree#13]
Title: Implementation of Breadth First Search using Graphs in python
Name: Apeksha M Prabhu
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
Implementation of Breadth First Search

BFS stands for Breadth First Search is a vertex based technique for finding a shortest path in graph. It uses a Queue data structure which follows first in first out. In BFS, one vertex is selected at a time when it is visited and marked then its adjacent are visited and stored in the queue. It is slower than DFS.

**Comment by prathimacode-hub** [comment]
Per one issue, you can work on only project. For other issue, you need to raise an issue again. So kindly let me know of the project topic you will be working out of the two given options above. You can work on only one issue at a time. @Apekshamarutip1

**Comment by prathimacode-hub** [comment]
So, it's a tree script. @Apekshamarutip1

**Comment by Apekshamarutip1** [comment]
Title: Implementation of Breadth First Search using Graphs in python
Name: Apeksha M Prabhu
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
Implementation of Breadth First Search and Depth First Search

BFS stands for Breadth First Search is a vertex based technique for finding a shortest path in graph. It uses a Queue data structure which follows first in first out. In BFS, one vertex is selected at a time when it is visited and marked then its adjacent are visited and stored in the queue. It is slower than DFS.

**Comment by Apekshamarutip1** [comment]
yes

**Comment by prathimacode-hub** [comment]
Ok, great issue assigned. Follow the project structure given while creating a project and template for PR. @Apekshamarutip1

**Comment by prathimacode-hub** [comment]
Change the details in your issue template, as the project title is changed now. @Apekshamarutip1

**Comment by Apekshamarutip1** [comment]
Done

**Comment by prathimacode-hub** [comment]
its been 22 days and no PR from you yet. @Apekshamarutip1

**Comment by prathimacode-hub** [comment]
Its been 27 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @Apekshamarutip1

**Comment by prathimacode-hub** [comment]
Exactly 30 days, Max time is 5 days. And you are unassigned from this issue as time is up for DCP program and you had held it for long time. Next time express interest only if you like to submit it timely. Holding an issue for long is never a right thing. @Apekshamarutip1
