### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#130]
---
Title: Depth First Search
About: The aim is to implement depth first search.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The purpose is to understand the functioning of DFS Algorithm in AI.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
