### ISSUE TITLE
Height of a BST

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#133]
---
Title: Height of a BST
About: The aim is to form a Binary Search Tree of the integers entered and display its height.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The purpose is to explore trees.

**Comment by Manasi2001** [comment]
@prathimacode-hub ma'am please assign me this issue :)

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001

**Comment by prathimacode-hub** [comment]
Its been 6 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @Manasi2001

**Comment by Manasi2001** [comment]
> Its been 6 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @Manasi2001

Sorry ma'am for the delay. I got stuck in some college assignments. Have made the PR now. 👍🏻
