### ISSUE TITLE
Divisor Sum

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#134]
---
Title: Divisor Sum
About: The aim is to calculate the sum of all the divisors of the entered number and display it.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The purpose is to explore arrays.

### I would like to work on this after the completion of my previous projects.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
