### ISSUE TITLE
Digit Recognizer 

### ISSUE THREAD

**Issue by anubhav201241** [prathimacode-hub/PyAlgo-Tree#135]
---
Title: Digit Recognizer
About: It Recognize Digit using Neural Network's Algorithm ANN
Name: Anubhav
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, it is as it comes under the PyALgo it's deep Learning algorithm ANN by which I'm creating a Digit recognizer 

**Describe the solution you'd like...**

Want to contribute to the repository.

**Describe alternatives you've considered?**

Implement it with another algorithm CNN 

**Additional context**

@prathimacode-hub Kindly assign this issue to me :)

**Comment by prathimacode-hub** [comment]
Ok, great to know but follow the guidelines. There are templates provided. Add a issue template along with project details to get issue assigned to you. You can go through README file of the project for better understanding. All the best. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub you can assign the issue to me as I already created the issue basically you understand what I want to contribute so you can assign this issue to me if you want :)

**Comment by prathimacode-hub** [comment]
Yes, I understood project. But its a formality you can just edit your comment, add your issue template and provide details. That is to know you as devincept participant. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub Now it's Good ?

**Comment by prathimacode-hub** [comment]
Yes, perfect. Issue assigned. @anubhav201241

**Comment by prathimacode-hub** [comment]
Its been 7 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub I have created the PR

**Comment by prathimacode-hub** [comment]
Time is up. @anubhav201241
