### ISSUE TITLE
Round Robin Scheduling

### ISSUE THREAD

**Issue by manvitha3579** [prathimacode-hub/PyAlgo-Tree#140]
---
|Topic|About|Name|Label|
|-|-|-|-|
|Robin Round Scheduling|In Round Rrobin Scheduling, each ready task runs turn by turn only in a cyclic queue for a limited time|[Manvitha  Chowdary Ramineni](https://github.com/manvitha3579)|Feature Request|
---
## Define you
- [x] DevIncept Participants

## Description
- Round robin is a pre-emptive algorithm
- The CPU is shifted to the next process after fixed interval time, which is called time quantum/time slice.
- The process that is preempted is added to the end of the queue.

Please assign this issue to me @prathimacode-hub mam

**Comment by prathimacode-hub** [comment]
Ok, but issue template isn't right yet. With this, its hard to know you as a DCP participant. So kindly add those checkup options in the template. Also address the changes to your earlier PR before you work on this. @manvitha3579

**Comment by manvitha3579** [comment]
> Ok, but issue template isn't right yet. With this, its hard to know you as a DCP participant. So kindly add those checkup options in the template. Also address the changes to your earlier PR before you work on this. @manvitha3579

Done mam

**Comment by prathimacode-hub** [comment]
Need few more changes in your earlier PR. I am assigning this issue but work on this after you done with the changes over there. @manvitha3579
