### ISSUE TITLE
Last index of an element in array.

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#141]
---
Title: last index  of an element in array.
About: I would like to add solution to this problem.
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like...**
I would like to add solution to this problem.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will be adding this in recursion folder by making a new folder named last index of array and initializing with a readme.

**Additional context**

**Comment by suy1968** [comment]
Please Assign me as I am a Contributor in Devincepts @prathimacode-hub

**Comment by siddhi-244** [comment]
> Please Assign me as I am a Contributor in Devincepts @prathimacode-hub

I have opened the issue ! Try for another one.

**Comment by prathimacode-hub** [comment]
Issue assigned. @siddhi-244
