### ISSUE TITLE
Trapping rainwater problem 

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#144]
--
Title: trapping rainwater problem 
About: I would like to add solution to this problem.
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like...**
I would like to add solution to this problem.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will be adding this in dp folder by making a new folder named trapping rainwater and initializing with a readme.

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned. @siddhi-244

**Comment by prathimacode-hub** [comment]
Its been 3 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @siddhi-244

**Comment by siddhi-244** [comment]
> Its been 3 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @siddhi-244

Will do it today !

**Comment by prathimacode-hub** [comment]
Update? @siddhi-244

**Comment by siddhi-244** [comment]
> Update? @siddhi-244

Done
