### ISSUE TITLE
Add binary search in python.

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#15]
---
Title: Binary Search in python
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
N.A.its a new feature.

**Describe the solution you'd like...**
I would like to add binary search solution.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

 through comments,I will explain my approach and add a readme for examples and Output ss

**Comment by prathimacode-hub** [comment]
You can proceed. Assigned. @siddhi-244

**Comment by siddhi-244** [comment]
Maam you haven't made a folder for searching shall I make it ?

**Comment by siddhi-244** [comment]
> Maam you haven't made a folder for searching shall I make it ?

@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, create a folder for "Searching"

**Comment by siddhi-244** [comment]
> Yes, create a folder for "Searching" @siddhi-244

Sure maam
