### ISSUE TITLE
Adding a recursion script

### ISSUE THREAD

**Issue by Jordistyd** [prathimacode-hub/PyAlgo-Tree#153]
Hi! I would love to add a recursion script in python to find the maximum number of paths from the start of a 2D array to a given point (i,j)
I have read the contributing guidelines.
Thank you :)

**Comment by prathimacode-hub** [comment]
Welcome to the repo. If you read the contributing guidelines, make sure you had read the README file of this project as well. To get issue assigned. You need to add issue template along with project details and specific project name unlike a general statement given here. Also let me know of who you are : LGMSoC participant or DCP participant or Contributor. Always provide details elaborately. If you need any guidance, don't hesitate to ask. @Jordistyd

**Comment by Jordistyd** [comment]
Great to be here! 
No problem I'm on it now, I'll upload the template as a reply
