### ISSUE TITLE
Recursion backtraking

### ISSUE THREAD

**Issue by Jordistyd** [prathimacode-hub/PyAlgo-Tree#155]
Title: Backtracking Recursion
Name: Yarden Galon
Label: Feature Request
Assignee: ''

Define You:

DevIncept Participant

- [ X] Contributor

Is your feature request related to a problem? Please describe.
It is a new feature.

Describe the solution you'd like...
In Programming, recursion is thought of as breaking a big complex problem into smaller more manegable problems.
The recursion method usually calls itself in order to reach a "Base case", where the problem is ultimatly solved.
I would like to demonstrate this concept by solving a common recursion problem.
Written in Python.
Finding the maximum paths through a certain maze, starting at the top left corner and ending at a specified spot

Approach to be followed (optional):
This script will provide the user with a built in maze and a set of coordiantes.
Using recursion I will demonstrate how the algorithm will check, one box at a time, possible ways to solve the maze.
If there are none it will return 0.
In order to get an even better idea of how it works, I encourge you to and change the maze and the coordiantes and see what results you get.

P.S Feel free to close my last issue, it felt neater to open a new one with your template :)

**Comment by prathimacode-hub** [comment]
Whooa, amazingly described. Issue assigned. Sure I would do that. @Jordistyd

**Comment by Jordistyd** [comment]
Awesome thank you!
Should have it done by tomorrow 
@prathimacode-hub
