### ISSUE TITLE
Recursion: Tower of Hanoi

### ISSUE THREAD

**Issue by aswinikalyan30** [prathimacode-hub/PyAlgo-Tree#157]
Title: Tower of Hanoi
About: Script for Tower of Hanoi problem, use graphics to visualize the same as a game
 Name: Aswini Kalyan(@aswinikalyan30) 
 Label: Feature Request 
Assignee: '' 
--- Define You: 
- [ ] DevIncept Participant 
- [x] Hacktoberfest Contributor
  ** Is your feature request related to a problem? Please describe. ** 
** I shall be working on the famous problem of Tower of Hanoi, which is going to take the number of disks, and visualize how the recursive problem works using pyglet module of python **

**Comment by prathimacode-hub** [comment]
Issue assigned to @aswinikalyan30

**Comment by prathimacode-hub** [comment]
Will you work on it as part of hacktober fest? @aswinikalyan30

**Comment by aswinikalyan30** [comment]
> Will you work on it as part of hacktober fest? @aswinikalyan30

Yes! But I'm not sure if it's allowed, since hacktoberfest is excluding all DSA related repos

**Comment by prathimacode-hub** [comment]
Ok that's upto you if your focus is only for hacktoberfest. No worries @aswinikalyan30
