### ISSUE TITLE
Rat in a Maze Problem using Backtracking

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#158]
🔴 Project Title : **Rat in a Maze problem solved using Backtracking algorithms**
🔴 Description : Finding out the shortest path to the destination using the matrix.
🔴 Name : Abhishek Sharma
🔴 Label : New Addition in the Backtracking directory.
🔴 Define me : 
- [x] Contributor (Hacktoberfest 2021)

🔴 Description and Approach : I will be using backtracking algorithms to solve the problem statement and finding out the minimum path from the starting to the destination of the given matrix. Here I will be using Python 3 as the programming language for coding purpose.

@prathimacode-hub Please assign me this issue, I want to contribute in this as a Hacktoberfest participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008
