### ISSUE TITLE
Water Jug Problem

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#16]
---
Title: Water Jug Problem
About: The aim is to solve Water Jug Problem using BFS or DFS as per user's choice using backtracking.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

You are given a 'm' liter jug and a 'n' liter jug where '0<m<n'. Both the jugs are initially empty. The jugs don't have markings 
to allow measuring smaller quantities. You have to use the jugs to measure 'd' liters of water where 'd<n'. Determine the minimum no of operations to be performed to obtain 'd' liters of water in one of jug.

**Describe the solution you'd like...**

Use BFS/DFS and backtracking in AI to solve the issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. It's a wonderful choice of the script. @Manasi2001
