### ISSUE TITLE
Campus Placements Analysis & Prediction.

### ISSUE THREAD

**Issue by ayushi424** [prathimacode-hub/PyAlgo-Tree#161]
Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

To provide script for the Campus placement analysis & prediction using a Machine Learning Algorithm in python.

**Approach to be followed:**

Implementing Decision Tree Regressor algorithm using a project as  Campus placement analysis & prediction which will include:
- Data preprocessing & exploring, 
- Data visualization, 
- Data training & 
- Model creation.

@prathimacode-hub Kindly assign me for this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @ayushi424
