### ISSUE TITLE
0-1 Knapsack Problem

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#162]
:red_circle: Title : **0-1 Knapsack Problem using Python 3 language**
:red_circle: Directory : **Knapsack**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2021
- [x] Contributor

:red_circle: Approach : To solve this 0-1 Knapsack problem, I will be using two major methods,
- Brute Force method
- Dynamic Programming method

After implementing all those methods I'll compare the time and space complexities of both the methods and provide a comparison of the methods for solving the 0-1 Knapsack problem.

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2021 participant.

**Comment by prathimacode-hub** [comment]
Assigned. @abhisheks008
