### ISSUE TITLE
Ugly Numbers using Dynamic Programming

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#164]
:red_circle: Title : **Ugly Numbers using Dynamic Programming**
:red_circle: Language used : **Python 3**
:red_circle: Directory : **Dynamic Programming**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2021
- [x] Contributor

:red_circle: **Description :**
Ugly numbers are numbers whose only prime factors are 2, 3 or 5. The sequence 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, … shows the first 11 ugly numbers. By convention, 1 is included. 
Given a number n, the task is to find n’th Ugly number.

Examples:  
```
Input  : n = 7
Output : 8

Input  : n = 10
Output : 12

Input  : n = 15
Output : 24

Input  : n = 150
Output : 5832 
```

:red_circle: Method : **Dynamic Programming**

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2021 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
