### ISSUE TITLE
0/1 Knapsack Problem

### ISSUE THREAD

**Issue by NeerajHazarika** [prathimacode-hub/PyAlgo-Tree#168]
- Title : 0/1 Knapsack problem
- Language : Python
- Directory : Dynamic programming
- Name : Neeraj Pratap Hazarika

✅ Hacktoberfest
✅ Contributor

## Description :

Write the solution code for the famous dynamic problem called 0/1 knapsack problem in python using top down dynamic programming approach

@prathimacode-hub please assign me this issue.

**Comment by manthan0227** [comment]
Can you assign this issue. I am doing competitive programming so i can solve this.

**Comment by NeerajHazarika** [comment]
@manthan0227 I opened this issue for myself, if u want to contribute to something else make your own issue and ask the maintainers to assign it to you.

**Comment by prathimacode-hub** [comment]
Issue assigned to @NeerajHazarika

**Comment by prathimacode-hub** [comment]
@manthan0227, you can come up with your own issue

**Comment by manthan0227** [comment]
Ok Ma'am
