### ISSUE TITLE
Subset Sum Problem using Dynamic Programming

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#171]
:red_circle: Title : **Subset Sum Problem using Dynamic Programming**
:red_circle: Language used : **Python 3**
:red_circle: Directory : **Dynamic Programming**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2021
- [x] Contributor

:red_circle: **Description :**
Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum. 

Example: 
```
Input: set[] = {3, 34, 4, 12, 5, 2}, sum = 9
Output: True  
There is a subset (4, 5) with sum 9.
```

:red_circle: Method : **Dynamic Programming**

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2021 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008
