### ISSUE TITLE
Bell Numbers Problem using Dynamic Programming

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#174]
:red_circle: Title : **Bell Numbers Problem using Dynamic Programming**
:red_circle: Language used : **Python 3**
:red_circle: Directory : **Dynamic Programming**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2021
- [x] Contributor

:red_circle: **Description :**
Given a set of n elements, find number of ways of partitioning it. 
Examples: 
```
Input:  n = 2
Output: Number of ways = 2
Explanation: Let the set be {1, 2}
            { {1}, {2} } 
            { {1, 2} }
```

:red_circle: Method : **Dynamic Programming**

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2021 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008
