### ISSUE TITLE
Caesar cipher Algorithm

### ISSUE THREAD

**Issue by manthan0227** [prathimacode-hub/PyAlgo-Tree#179]
Ma'am i have done caesar cipher algorithm before assigning the issue. And i have sent the pull request to you. So please assigning the caesar cipher algorithm. And check my pull request of caesar cipher.

**Comment by manthan0227** [comment]
- Title: Caesar Cipher
- Language: Python
- Directory: Cipher
- Name: Manthan Nagpurkar

☑Hacktoberfest
☑Contributor

## Description
To implement the algorithm of Caesar Cipher in python language. This algorithm is used for Encrypt and Decrypt the message.

@prathimacode-hub Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned to @manthan0227
