### ISSUE TITLE
Sudoku Solver using Backtracking

### ISSUE THREAD

**Issue by dhruv-varshney** [prathimacode-hub/PyAlgo-Tree#18]
Title: Sudoku Solver
About: The aim is to solve any sudoku  by using Backtracking
Name: Dhruv Varshney
Label: Feature Request
Assignee: 'dhruv-varshney'

Define You:

 

- [x] DevIncept Participant

 

- [x] Contributor

Is your feature request related to a problem? Please describe.

There is a grid that contains nine squares which are then subdivided into a further nine smaller squares in such a way that every number appears once in each horizontal line, vertical line, and square. The grid is basically a 9*9 matrix and the empty small boxes will have a value of "0" which get replaced by the correct value which satisfies all the sudoku rules

Describe the solution you'd like...

I will use backtracking to solve this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @dhruv-varshney
