### ISSUE TITLE
Movie Classification

### ISSUE THREAD

**Issue by ayushi424** [prathimacode-hub/PyAlgo-Tree#180]
Define You:

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

To provide script for the Movie Classification using a Machine Learning Algorithm in python.

**Approach to be followed:**

Implementing KNN algorithm using a project as Movie Classification  which will include:
- Data preprocessing & exploring, 
- Data training & 
- Model creation.

@prathimacode-hub Kindly assign me for this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushi424
