### ISSUE TITLE
Count set bits in an integer

### ISSUE THREAD

**Issue by NeerajHazarika** [prathimacode-hub/PyAlgo-Tree#181]
- Title : Count set bits in an integer
- Language : Python
- Directory : Bit Manipulation
- Name : Neeraj Pratap Hazarika

- [x] Hacktoberfest
- [x] Contributor

## Description :

Write an efficient program to count the number of 1s in the binary representation of an integer.

@prathimacode-hub please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @NeerajHazarika
