### ISSUE TITLE
Face Detection Using Digital Image Processing

### ISSUE THREAD

**Issue by Lashuk1729** [prathimacode-hub/PyAlgo-Tree#182]
- Title: Face Detection Algorithm
- Language: Python
- Directory: Digital Image Processing
- Name: Kushal Borkar

- [x] Hacktoberfest
- [x] Contributor

Description :
Write the Face Detection program using Haar Cascades Algorithm.

@prathimacode-hub please assign me this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Lashuk1729

**Comment by prathimacode-hub** [comment]
By when are you expected to do changes? Fest is about to end? @Lashuk1729
