### ISSUE TITLE
Gold Mine Problem using Dynamic Programming

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#185]
:red_circle: Title : **Gold Mine Problem using DP**
:red_circle: Directory : **Dynamic Programming**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2021
- [x] Contributor

:red_circle: Approach : To solve this problem, I'll be using Dynamic approach.

🔴 Problem Statement : Given a gold mine of n*m dimensions. Each field in this mine contains a positive integer which is the amount of gold in tons. Initially the miner is at first column but can be at any row. He can move only (right->,right up /,right down\) that is from a given cell, the miner can move to the cell diagonally up towards the right or right or diagonally down towards the right. Find out maximum amount of gold he can collect. 
Examples: 
```
Input : mat[][] = {{1, 3, 3},
                   {2, 1, 4},
                  {0, 6, 4}};
Output : 12 
{(1,0)->(2,1)->(1,2)}

Input: mat[][] = { {1, 3, 1, 5},
                   {2, 2, 4, 1},
                   {5, 0, 2, 3},
                   {0, 6, 1, 2}};
Output : 16
(2,0) -> (1,1) -> (1,2) -> (0,3) OR
(2,0) -> (3,1) -> (2,2) -> (2,3)
```

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2021 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008
