### ISSUE TITLE
Determining DNA Health

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#19]
---
Title: Determining DNA Health Problem
About: Find and print the respective total healths of the unhealthiest (minimum total health) and healthiest (maximum total health) strands of DNA as two space-separated values on a single line, where gene sequence is given as an array input. 
Name: Abhishek Sharma
Label: Feature Request
Assignee: abhisheks008''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
An array of beneficial gene strings `genes = [g0, g1,...,gn-1]`, . Note that these gene sequences are not guaranteed to be distinct.
An array of gene health values, `health = [h0,h1,...,hn-1]` , where each **_h<sub>i</sub>_**  is the health value for gene .
A set of **_s_**  DNA strands where the definition of each strand has three components, **_start_** ,**_end_** , and **_d_**, where **_d_** string  is a DNA for which **_g<sub>start</sub>_**,....,**_g<sub>end</sub>_** genes  are healthy.

Find and print the respective total healths of the unhealthiest (minimum total health) and healthiest (maximum total health) strands of DNA as two space-separated values on a single line.

Problem statement link : https://www.hackerrank.com/challenges/determining-dna-health/problem

**Describe the solution you'd like...**
Here I am going to use Aho-Corasick algorithm for groups of genes and Knuth–Morris–Pratt algorithm for single genes. To lower memory consumption and to use processor cache better, processing grouped not as all relevant searches for one query together but as all queries for one search element (gene group or single gene) together. The time complexity of this approach is **_O(L<sub>g</sub> . s . d + n<sup>(1/d)</sup> . L<sub>q</sub>)_**

Please assign me this issue @prathimacode-hub 

This problem will be added in the **Strings repository**

Language : Python 3

**Comment by prathimacode-hub** [comment]
You can proceed. It's a unique script you had choosen. @abhisheks008
