### ISSUE TITLE
Human Detection and Counting

### ISSUE THREAD

**Issue by akash435** [prathimacode-hub/PyAlgo-Tree#191]
---
Title: Human Detection and Counting
About: Here will detect humans in image or video and will also count  max no. of people in it.
Name: Akash Rajak
Label: Feature Request
Assignee: ''

---

Define You:

- [X] Hacktoberfest2021 Participant 
- [ ] Contributor

---

Description:

In this will create a GUI based model using tkinter and in the backend part will use opencv and tensorflow.
here user will be asked to select any image or video, and application will detect the maximum people in image or video, and also gives the count at the end.

**Comment by akash435** [comment]
@prathimacode-hub can i work on this under hacktoberfest'21.

**Comment by prathimacode-hub** [comment]
Yes, sure. issue assigned to @akash435
