### ISSUE TITLE
Heart failure prediction using Adaboost & XGboost

### ISSUE THREAD

**Issue by SaloniThete** [prathimacode-hub/PyAlgo-Tree#194]
Heart failure prediction using Adaboost & XGboost.
kindly Assign me as a contributor to HACKTOBERFEST 2021.
Kindly Review & merge the PR under HACKTOBERFEST 2021
Thank you.
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Kindly follow the issue template given and you have to use multiple algorithms and compare the accuracy for the prediction. @SaloniThete

**Comment by SaloniThete** [comment]
Sure I'll make the required changes.
