### ISSUE TITLE
Inorder, Preorder, & Postorder traversal

### ISSUE THREAD

**Issue by motasimmakki** [prathimacode-hub/PyAlgo-Tree#198]
Title: Inorder, Preorder, & Postorder traversal
Language: Python
Category: Tree Traversal Algorithms

- [x] Hacktoberfest 2021'
- [x] Contributor

Description:
Algorithms for Inorder, Preorder, and Postorder traversal of Binary tree.

**Comment by motasimmakki** [comment]
@prathimacode-hub
Kindly assign this to me under Hachtoberfest 2021'

**Comment by prathimacode-hub** [comment]
Issue assigned @motasimmakki
