### ISSUE TITLE
Activity Selection Problem [Folder: Greedy]

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#204]
:red_circle: Title : **Activity Selection Problem**
:red_circle: Directory : **Greedy Algorithm**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2022
- [x] Contributor

:red_circle: Approach : To solve this problem, I'll be using Greedy approach.

🔴 Problem Statement : You are given n activities with their start and finish times. Select the maximum number of activities that can be performed by a single person, assuming that a person can only work on a single activity at a time. 
Examples: 
```
Input:
Consider the following 3 activities sorted by finish time.
start[]  =  {10, 12, 20}
finish[] =  {20, 25, 30}

Output: {0, 2}

Explanation:
A person can perform at most two activities. The maximum set of activities that can be executed is {0, 2} [ These are indexes in start[] and  finish[] ]
```

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2022 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008. You can proceed.
