### ISSUE TITLE
Web Scraping using BeautifulSoup Library of Python

### ISSUE THREAD

**Issue by singhmansi25** [prathimacode-hub/PyAlgo-Tree#205]
☑️ **Title :** Web Scraping using BeautifulSoup in Python
☑️ **Name :** Mansi Singh
☑️ **Contribution Type :** 

- [ ]  Hacktoberfest2022 Participant
- [ ]  Contributor

☑️ **Assignee :** Prathima Kadari
☑️ **Approach :** I will be using various web scraping libraries in python to scrape data from websites.

@prathimacode-hub Please assign me this issue, as I want to participate in Hacktoberfest 2022.

**Comment by prathimacode-hub** [comment]
@singhmansi25, you are referring to wrong repository. You can create this issue in the repo : https://github.com/prathimacode-hub/Awesome_Python_Scripts. Glad to know of your interest. While creating an issue, just be specific with mentioning what's the project script you'll be contributing. Web Scraping is a vast thing.

**Comment by singhmansi25** [comment]
Ok, Thank you @prathimacode-hub 
I will close this issue and create in the specified directory.
