### ISSUE TITLE
Depth-first Search (DFS) Python

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/PyAlgo-Tree#207]
---
Title: Depth-first Search(DFS) in Python
Directory: Graph
Name: Satyam Tripathi 

---

Define You:

- [X] Hacktoberfest2022 Participant 
- [X] Contributor

Problem: Write to Program in Python to implement Depth-first search in a graph.
```
Input:
graph = {
        0: [2],
        1: [2, 3],
        2: [0, 1, 4],
        3: [1, 4],
        4: [2, 3]
    }

Output:
Depth-first search: [0, 2, 1, 3, 4]
```
@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2022 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Iamtripathisatyam
