### ISSUE TITLE
Breadth First Search

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/PyAlgo-Tree#209]
---
Title: Breadth-First Search
Directory: Graph
Name: Satyam Tripathi 

---

### Define You:

- [X] Hacktoberfest2022 Participant 
- [X] Contributor

### Problem:
 Write to program in Python to implement a Breadth-first search. Breadth-first search (BFS) is used to solve many problems, including finding the shortest path in a graph or solving puzzle games such as Rubik’s Cubes.

### Input:
```
graph = {
    'A': ['B', 'C', 'D'],
    'B': ['A'],
    'C': ['A', 'D'],
    'D': ['A', 'C', 'E'],
    'E': ['D'],
}
```

### Output:
```
Breadth-first search: A B C D E
```
@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2022 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Iamtripathisatyam. Go ahead.

**Comment by Iamtripathisatyam** [comment]
> Issue assigned to @Iamtripathisatyam. Go ahead.

Thank you!
