### ISSUE TITLE
Huffman Coding using Greedy Approach

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#214]
:red_circle: Title : **Huffman Coding**
:red_circle: Directory : **Greedy Algorithm**
:red_circle: Name : **Abhishek Sharma**
:red_circle: Contribution type : 
- [x] Hacktoberfest 2022
- [x] Contributor

:red_circle: Approach : To solve this problem, I'll be using Greedy approach.

🔴 Problem Statement : We know that each character is a sequence of 0's and 1's and stores using 8-bits. The mechanism is called fixed-length encoding because each character uses the same number of fixed-bit storage.
Here, a question ascends, is it possible to reduce the amount of space required to store a character?

@prathimacode-hub Please assign me this issue, I'll be contributing as a Hacktoberfest 2022 participant.

**Comment by prathimacode-hub** [comment]
Issue assigned to @abhisheks008
