### ISSUE TITLE
Priority Queue

### ISSUE THREAD

**Issue by Iamtripathisatyam** [prathimacode-hub/PyAlgo-Tree#216]
---
Title: Priority Queue
Directory: Queue
Name: Satyam Tripathi 

### Define You:

- [X] Hacktoberfest2022 Participant 
- [X] Contributor

### Problem:
We have to implement the Priority Queue. We will see its working, code, and explanation.

---
@prathimacode-hub, Please assign me this issue.

**Comment by prathimacode-hub** [comment]
You can be specific with 1 queue for each issue. Can you change the issue accordingly to get it assigned. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
> You can be specific with 1 queue for each issue. Can you change the issue accordingly to get it assigned? @Iamtripathisatyam

Done

**Comment by prathimacode-hub** [comment]
Issue assigned to @Iamtripathisatyam
