### ISSUE TITLE
Predicting House Prices

### ISSUE THREAD

**Issue by abhisheks008** [prathimacode-hub/PyAlgo-Tree#24]
---
Title: Predicting House Prices
Algorithm : Multiple Linear Regression
About: Predicting the prices of the houses based given parameters.
Name: Abhishek Sharma
Label: Feature Request
Assignee: abhisheks008''

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Charlie wants to buy a house. He does a detailed survey of the area where he wants to live, in which he quantifies, normalizes, and maps the desirable features of houses to values on a scale of `0` to `1` so the data can be assembled into a table. If Charlie noted `F` features, each row contains `F` space-separated values followed by the house price in dollars per square foot (making for a total of `F+1` columns). If Charlie makes observations about `H` houses, his observation table has `H` rows. This means that the table has a total of `(F + 1) x H` entries.

Unfortunately, he was only able to get the price per square foot for certain houses and thus needs your help estimating the prices of the rest! Given the feature and pricing data for a set of houses, help Charlie estimate the price per square foot of the houses for which he has compiled feature data but no pricing.

Now predict the house using the multiple linear regression algorithm

Problem statement link : https://www.hackerrank.com/challenges/predicting-house-prices/problem

Difficulty at HackerRank : Expert

**Describe the solution you'd like...**
`I am going to use Multiple Linear Regression as per the question given`

Please assign me this issue @prathimacode-hub 

This problem will be added in the `Artificial Intelligence repository`

Language : Python 3

**Comment by prathimacode-hub** [comment]
Issue assigned. @abhisheks008
