### ISSUE TITLE
Queue 

### ISSUE THREAD

**Issue by priyankav0107** [prathimacode-hub/PyAlgo-Tree#29]
Title: implementation of queue using list
Name: PRIYANKA V
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
There are various ways to implement a queue in Python. This article covers the implementation of queue using data structures and modules from Python library.
Queue in Python can be implemented by the following ways:
list
collections.deque
 queue.Queue
 

Describe alternatives you've considered?

Approach to be followed (optional):

This program contains the  implementation of queue using list :
List is a Python’s built-in data structure that can be used as a queue. Instead of enqueue() and dequeue(), append() and pop() function is used. However, lists are quite slow for this purpose because inserting or deleting an element at the beginning requires shifting all of the other elements by one, requiring O(n) time.

**Comment by prathimacode-hub** [comment]
Can you be specific about the issue. @priyankav0107

**Comment by priyankav0107** [comment]
i will be implementing  queue using python

**Comment by priyankav0107** [comment]
Title:  Queue using Python
Name: PRIYANKA V
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
There are various ways to implement a queue in Python. This article covers the implementation of queue using data structures and modules from Python library.
Queue in Python can be implemented by the following ways:
list
collections.deque
queue.Queue

Describe alternatives you've considered?

Approach to be followed (optional):

This program contains the implementation of queue using list :
List is a Python’s built-in data structure that can be used as a queue. Instead of enqueue() and dequeue(), append() and pop() function is used.

**Comment by prathimacode-hub** [comment]
Issue assigned. @priyankav0107
