### ISSUE TITLE
Contribute to this repo 🔔

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/PyAlgo-Tree#3]
Contribute to this respository to shower your love towards this project and getting started with Open Source/Github.

**Comment by bhagyashree-06** [comment]
I am interested!

**Comment by prathimacode-hub** [comment]
Are you a DevIncept participant? @bhagyashree-06

**Comment by bhagyashree-06** [comment]
> Are you a DevIncept participant? @bhagyashree-06

yes, I am

**Comment by prathimacode-hub** [comment]
That's great, glad to see your interest to contribute. You can start contributing from 10th of July as program would count from then. Meanwhile go through the README and CONTRIBUTING GUIDELINES. Any queries, don't hesitate to ask. @bhagyashree-06

**Comment by bhagyashree-06** [comment]
Sure, thank you! @prathimacode-hub

**Comment by thebhavana** [comment]
Review #184 
@prathimacode-hub
