### ISSUE TITLE
Singly Linked List

### ISSUE THREAD

**Issue by nknantha** [prathimacode-hub/PyAlgo-Tree#31]
---
Title: Singly Linked List
About: Singly Linked List implementation by nodes.
Name: NanthaKumar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] **DevIncept Participant**
- [ ] ~~Contributor~~

**Is your feature request related to a problem? Please describe.**
No. I wants to add new feature.

**Describe the solution you'd like...**
A Singly Linked List which is implemented by nodes, consist of basic linked opertions like add, delete, update, insert.

**Comment by prathimacode-hub** [comment]
Issue assigned. @nknantha
