### ISSUE TITLE
All indices of a number in array.

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#33]
---
Title: All indices of an element in array.
About: I would like to add solution to this problem.
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like...**
I would like to add solution to this problem.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**
I will be adding this in array folder by making a new folder named all indices of array and initializing with a readme.

**Additional context**

**Comment by siddhi-244** [comment]
Please assign this to me under dcp

**Comment by prathimacode-hub** [comment]
Issue assigned. @siddhi-244
