### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#34]
---
Title: Tic Tac Toe Game
About: The aim is to build a game of Tic Tac Toe using backtracking algorithm, MiniMax.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Minimax is a kind of backtracking algorithm. It searches, recursively, the best move that leads the Max player to win or not lose (draw). It considers the current state of the game and the available moves at that state, then for each valid move, it plays (alternating min and max) until it finds a terminal state (win, draw or lose). I would like to use this for building the game.

**Describe the solution you'd like...**

Use MiniMax in AI to solve the issue.

**Comment by prathimacode-hub** [comment]
You can proceed. @Manasi2001
