### ISSUE TITLE
Knight's Tour

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#36]
---
Title: Knight's Tour
About: The aim is to come up with a solution for this problem using backtracking.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The motive is to check whether it is possible for a Knight to visit each cell of the N*N chessboard without visiting any cell twice starting from (X, Y) position. User will enter the chessboard size and a solution (if exists) will be printed.

**Describe the solution you'd like...**

Use backtracking to solve the issue.

**Comment by prathimacode-hub** [comment]
Assigned. @Manasi2001
