### ISSUE TITLE
N Queens

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#38]
---
Title: N Queens
About: The aim is to come up with a solution for this problem using backtracking.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The motive is to place N queens in a N*N Chessboard such that no two queens attack each other. A queen is said to be attacked by another queen if they share same diagonal(right/left), Row or Column.

**Describe the solution you'd like...**

Use backtracking to solve the issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
