### ISSUE TITLE
Fibonacci Search 

### ISSUE THREAD

**Issue by neha030** [prathimacode-hub/PyAlgo-Tree#4]
I want to add the python code for Fibonacci Search under DCP'21
Please assign me this issue

**Comment by prathimacode-hub** [comment]
Welcome, contribution period would start from tomorrow. You can get an issue assigned tomorrow, but to raise an issue and PR, there are templates providd int he README file of the project. @neha030

**Comment by prathimacode-hub** [comment]
Hey, if you want to work on this issue, kindly raise a new issue using the template provided in README file of the project. @neha030

**Comment by Sri-vishnu-r1431** [comment]
I want to work on this issue kindly assign me this issue under devincept '21

**Comment by prathimacode-hub** [comment]
Raise up a new issue using the issue template provided in README file of the project. Changes the modifications according to your project. Else you refer with assigned issues to see how template looks like one. @Sri-vishnu-r1431
