### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by sushmithanjayaram** [prathimacode-hub/PyAlgo-Tree#40]
Title:  Strings
Name: Sushmitha N J
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
In Python, Strings are arrays of bytes representing Unicode characters. However, Python does not have a character data type, a single character is simply a string with a length of 1. string is an immutable sequence data type.  Square brackets can be used to access elements of the string.
Describe alternatives you've considered?

Approach to be followed (optional):

This program contains of operations on string methods:

isupper() | Returns True if all characters in the string are upper case
lower() method returns a string where all characters are lower case.
replace() method replaces a specified phrase with another specified phrase.
isnumeric() method returns True if all the characters are numeric (0-9), otherwise False.

**Comment by prathimacode-hub** [comment]
Can you be particular about the issue, as strings is itself a vast topic. Just edit up with the project you will be working and change details accoringly. Be specific about the topic. @sushmithanjayaram

**Comment by sushmithanjayaram** [comment]
I will implement 
Isupper()
lower()
replace()
Isnumeric() 
Methods

**Comment by prathimacode-hub** [comment]
Good work, issue assigned. @sushmithanjayaram

**Comment by prathimacode-hub** [comment]
Its been 20days and no PR from you yet. @sushmithanjayaram

**Comment by prathimacode-hub** [comment]
Its been 25 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @sushmithanjayaram

**Comment by prathimacode-hub** [comment]
Exactly 27 days, Max time is 5 days. And you are unassigned from this issue as time is up for DCP program and you had held it for long time. Next time express interest only if you like to submit it timely. Holding an issue for long is never a right thing. @sushmithanjayaram
