### ISSUE TITLE
Caesar Cipher

### ISSUE THREAD

**Issue by photon149** [prathimacode-hub/PyAlgo-Tree#41]
Title: Caesar Cipher
About: The aim is to come up with a decryption/encryption to the entered encrypted/decrypted value using caesar cipher
Name: Shiwansh Raj
Label: Feature Request
Assignee: ''

Define You:

 ✅DevIncept Participant
 Contributor

Is your feature request related to a problem? Please describe.
The motive is to decrypt  or encrypt the entered string by the user , using Caesar cipher technique. The key value shall also be entered by the user as well as the user will be given to choice to decrypt or encrypt.

Describe the solution you'd like...
Create two classes which will be used to decrypt the entered string and encrypt the string , according to the choice of the user.

Decrypting/Encrypting  input string entered by the user .

Input values : ENCRYPTED/DECRYPTED STRING , KEY VALUE

Please Assign me this issue under DEVINCEPT 21

**Comment by prathimacode-hub** [comment]
Issue assigned. @photon149
