### ISSUE TITLE
Transposition Cipher

### ISSUE THREAD

**Issue by RC2208** [prathimacode-hub/PyAlgo-Tree#42]
Title: Transposition Cipher
About: Code for decryption/encryption of string using Transposition cipher. 
Name: Ritika Chand
Label: Feature Request
Assignee: ''

Define You:

✅DevIncept Participant
**Contributor**

**Is your feature request related to a problem? Please describe.**

The motive is to decrypt or encrypt the entered string by the user , using Transposition cipher technique. The key value shall also be entered by the user and the user has the choice to decrypt or encrypt. Transposition cipher can be done either by shuffling the columns or without shuffling. 

**Describe the solution you'd like...**
Create two classes which will be used to decrypt the entered string and encrypt the string , according to the choice of the user. 

Input values : ENCRYPTED/DECRYPTED STRING , KEY VALUE

Please Assign me this issue under DEVINCEPT 21

**Comment by prathimacode-hub** [comment]
Wonderful choice, issue assigned. @RC2208
