### ISSUE TITLE
Check Palindrome with recursion

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#45]
Title: Check Palindrome with recursion
About: The aim is to come up with a solution for this problem using Recursion.
Name: Pushpit Jain
Label: Feature Request
---

Define You:

✅ DevIncept Participant
    Contributor

Is your feature request related to a problem? Please describe.
Palindromes are very famous and required many a times. The motive is to check if the entered string by the user is a palindrome using recursion.

Describe the solution you'd like...
Create a function which returns True or False if the input string is palindrome or not using string slicing and recursion.

Input values : string
Output value : true or false

Please Assign me this issue under DEVINCEPT 21

**Comment by prathimacode-hub** [comment]
Issue assigned. @pushpit-J19
