### ISSUE TITLE
Array Operations.

### ISSUE THREAD

**Issue by SANJAY-NT** [prathimacode-hub/PyAlgo-Tree#5]
Can I take up the array structure and Add all operations with code and a readme explaining all the details.

**Comment by prathimacode-hub** [comment]
You can work on only 1 issue at a time. So decide the issue you would work on first. And follow the issue template given to get an issue assigned to you. All the template are provided in README file of the project. Also go through the README and CONTRIBUTING GUIDELINES. You'll gain clarity on it. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
I would like to work on Arrays first.

**Comment by prathimacode-hub** [comment]
Ok, add up the issue template and modify according to the project you're taking up. I shall assign once you do that. 
@SANJAY-NT

**Comment by SANJAY-NT** [comment]
I don't know where is the templet can i get some link for the same.

**Comment by prathimacode-hub** [comment]
Be specific about the project title. You can work on only issue at a time. Change the issue title to your project title you will be working on. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
I  updated the title with the operations i will be working on.

**Comment by prathimacode-hub** [comment]
The issue title is still not specific. What's the operations you will be working on? Change it to the project title. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
Yes ma'am I updated the issue heading.

**Comment by prathimacode-hub** [comment]
Add the issue title as "Array Operations. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
Yes Mam.

**Comment by prathimacode-hub** [comment]
Issue assigned. @SANJAY-NT
