### ISSUE TITLE
Cryptarithmetic Problem

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#52]
---
Title: Cryptarithmetic Problem
About: The aim is to solve the Cryptarithmetic Problem: SEND MORE MONEY.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The motive is to solve a cryptarithmetic problem. Cryptarithmetic problems are mathematical puzzles where digits are replaced by symbols. And the aim is to find unique digits(0-9) that the letters should represent, such that they satisfy the given constraints.

**Describe the solution you'd like...**

Use backtracking to solve the issue.

**Comment by prathimacode-hub** [comment]
Issue asssigned. @Manasi2001
