### ISSUE TITLE
Expression tree Evaluation

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#53]
---
Title: Expression tree Evaluation
About: Aim is to write a code in python to evaluate the expression tree
Name: Pushpit Jain
Label: Feature Request
Assignee: 

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Expression trees are used to represent expressions in form of a tree. For a mathematical expression, its evaluation will give the equivalent result.

**Describe the solution you'd like...**

Use tree structure to create an expression tree, with each node being a class object. Then use recursive approach to solve the expression.

Please assign me this issue under Devincept21

**Comment by suy1968** [comment]
Please assign me this issue as I am a contributor under Devincept21.
I used Python 3 @pushpit-J19

**Comment by prathimacode-hub** [comment]
@suy1968, pushpit has no access to assign this issue to you. He is as well a devincept participant similar to you. The issues are assigned on first come first serve basis. So he would get this issue assigned.

@pushpit-J19 Issue is assigned to you. You can proceed working. @pushpit-J19
