### ISSUE TITLE
Customer Segmentation using K-Means Clustering Algorithm

### ISSUE THREAD

**Issue by drishtibaranwal** [prathimacode-hub/PyAlgo-Tree#55]
Title:  K-Means Clustering Algorithm for customer segmentation
About: Aim is to write a code in python to divide the customers in different groups. 
Name: Drishti Baranwal 
Label: Feature Request
Assignee:

**Comment by prathimacode-hub** [comment]
You can work on only 1 issue at a time and an issue is already assigned to you. Kind check on to it. @drishtibaranwal
