### ISSUE TITLE
Graph Coloring Problem

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#60]
---
Title: Graph Coloring Problem
About: The aim is to solve Graph Coloring Problem.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The motive is to solve graph coloring problem. Given an undirected graph and an integer M. The task is to determine if the graph can be colored with at most M colors such that no two adjacent vertices of the graph are colored with the same color.

**Describe the solution you'd like...**

Use backtracking to solve the issue.

**Comment by prathimacode-hub** [comment]
Template is showing the details of your previous issue. Kindly correct it. @Manasi2001

**Comment by Manasi2001** [comment]
> Template is showing the details of your previous issue. Kindly correct it. @Manasi2001

I'm sorry. Corrected now ma'am.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
