### ISSUE TITLE
Infix to Postfix Conversion

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#62]
---
Title: Infix to Postfix Conversion
About: Aim is to perform the conversion using stacks 
Name: Pushpit Jain
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

It is an important application of stack and gives many advantages over infix expression like -
Any formula can be expressed without parenthesis.
It is very convenient for evaluating formulas on computer with stacks.
Postfix expression doesn't has the operator precedence.
Postfix is slightly easier to evaluate.
It reflects the order in which operations are performed.
You need to worry about the left and right associativity

**Describe the solution you'd like...**
I will use the stacks data structure, to store the operators and convert the infix expression to equivalent postfix expression

Please assign me this issue under Devincept21

**Comment by prathimacode-hub** [comment]
You can proceed. @pushpit-J19
