### ISSUE TITLE
Subset Sum

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#63]
---
Title: Subset Sum
About: The aim is to solve Subset Sum Problem.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The motive is to solve subset sum problem. From a list of integers, the aim is to check and return a set of integers whose sum will be equal to the target value K.

**Describe the solution you'd like...**

Use backtracking to solve the issue.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
