### ISSUE TITLE
8 Puzzle Problem using A star Algorithm

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#65]
---
Title: 8 Puzzle Problem using A star Algorithm
About: The aim is to solve 8 Puzzle Problem using A star Algorithm in AI.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

An instance of the n-puzzle game consists of a board holding n^{2}-1 distinct movable tiles, plus an empty space. The tiles are numbers from the set 1,..,n^{2}-1. For any such board, the empty space may be legally swapped with any tile horizontally or vertically adjacent to it. In this assignment, the blank space is going to be represented with the number 0. Given an initial state of the board, the combinatorial search problem is to find a sequence of moves that transitions this state to the goal state; that is, the configuration with all tiles arranged in ascending order 0,1,..,n^{2}-1.

**Describe the solution you'd like...**

Use an AI algorithm, A* to solve the problem.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
