### ISSUE TITLE
Fibonacci series by using Recursion

### ISSUE THREAD

**Issue by dhruv-varshney** [prathimacode-hub/PyAlgo-Tree#67]
Title: Fibonacci series
About: The aim is to use recursion to get a Fibonacci series till 'n' 
Name: Dhruv Varshney
Label: Feature Request
Assignee: 'dhruv-varshney'

Define You:

 

- [x] DevIncept Participant

- [x]  Contributor

Is your feature request related to a problem? Please describe.

The Fibonacci numbers are  the sequence of numbers that is defined by the recurrence relation 

Fn = Fn-1 + Fn-2

Describe the solution you'd like...

I will use Recursion to solve this issue.

**Comment by dhruv-varshney** [comment]
I am raising the issue for the second time in this project.

**Comment by dhruv-varshney** [comment]
> Hello there! 👋🏻 Welcome to the PyAlgo-Tree! 
> Thank you and congrats  for opening your very first issue in this project. Please adhere to our [Code of Conduct](https://github.com/prathimacode-hub/PyAlgo-Tree/blob/main/CODE_OF_CONDUCT.md). 👍🏻 You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/prathimacode-hub/PyAlgo-Tree/blob/main/.github/pullrequest_template.md).
> Feel free to get in touch with me through social media handles. Hope to see you there!

I am raising the issue for the second time in this project.

**Comment by prathimacode-hub** [comment]
Issue assigned, I guess bot is out of control. 😆@dhruv-varshney
