### ISSUE TITLE
I want to add merge sort  algorithm

### ISSUE THREAD

**Issue by AlexAdvent** [prathimacode-hub/PyAlgo-Tree#68]
I want to add a merge sort algorithm based on divide and conquer.

**Comment by prathimacode-hub** [comment]
Are you a LGMSOC or Devincept participant? @AlexAdvent

**Comment by AlexAdvent** [comment]
yes, I'm a Devincept participant.

**Comment by prathimacode-hub** [comment]
How would I know if you are, only if you follow the guidelines i could  right? Kindly read the README and CONTRIBUTING GUIDELINES. There are templates provided to follow for issue, PR and README. Add the issue template here in comments, fill the details appropriately along with your approach. I could then assign the issue to you. @AlexAdvent

**Comment by prathimacode-hub** [comment]
And also you can work on only 1 issue at a time @AlexAdvent

**Comment by AlexAdvent** [comment]
---
Title: Merge Sort Algorithm
About: Sorting Algorithm time Complexity O(logn)
Name: Rajpurohit Vijeshkumar
Label: Feature Request
Assignee: ''

---

Define You:

- [*] DevIncept Participant 
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**
No. I want to add a new feature.


**Describe the solution you'd like...**
Merge Sort is based on the divide and conquer algorithm it divides the input array into two halves and called itself.




**Approach to be followed (optional):**



**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned. @AlexAdvent
