### ISSUE TITLE
Ordered list

### ISSUE THREAD

**Issue by sujay2306** [prathimacode-hub/PyAlgo-Tree#7]

**Comment by prathimacode-hub** [comment]
Please  follow the issue template given in README to get issue assigned
And also be particular about the project title give to the issue. Don't generalize it. @sujay2306

**Comment by sujay2306** [comment]
Title: list Creation , insertion and deletion operation in Python

Name: Sujay KS

Label: Feature Request

Define You:

 DevIncept Participant

 Contributor

Describe of changes I want to make

I would like to add all the list  implementations methods and operation on the same using python

Type of change

What sort of change have you made:

 New feature (non-breaking change which adds functionality)

Approach

I would Define the Operation and explain the implementation with appropriate comment and a read me with detailed labels and approach.

**Comment by prathimacode-hub** [comment]
Per one issue, you can work on only 1 script. So decide on what kind of list you would like to work on, change the issue title and template details accordingly. Also, add a tick mark beside devincept participant in template. Do these changes to get this issue assigned. @sujay2306

**Comment by prathimacode-hub** [comment]
What's the project title? Please do the changes asked. @sujay2306

**Comment by sujay2306** [comment]
Title: Insertion operation in list
Name: Sujay KS
Label: Feature Request
Assignee: ''

Define You:

✅ DevIncept Participant
Contributor

Is your feature request related to a problem? Please describe.
Its a new feature.

Describe the solution you'd like...
Lists are used to store multiple items in a single variable.
Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.
Lists are created using square brackets:[ ]

Describe alternatives you've considered?

Approach to be followed (optional):

This program contains  of operations on  a  orderd List:
1. insert()
2. remove()
3. append()
4. extend ()

**Comment by prathimacode-hub** [comment]
So this project title should be "Ordered List". Add this as issue title. @sujay2306

**Comment by sujay2306** [comment]
done

**Comment by prathimacode-hub** [comment]
Issue assigned, You can proceed. @sujay2306

**Comment by sujay2306** [comment]
thank you

**Comment by prathimacode-hub** [comment]
Its been 23 days and no PR from you yet. @sujay2306

**Comment by prathimacode-hub** [comment]
Its been 28 days. 9th is the last date to accept PR's. If you wouldn't do it by then, obviously you can submit later but points won't be counted towards DCP program. @sujay2306

**Comment by prathimacode-hub** [comment]
Exactly 30 days, Max time is 5 days. And you are unassigned from this issue as time is up for DCP program and you had held it for long time. Next time express interest only if you like to submit it timely. Holding an issue for long is never a right thing. @sujay2306
