### ISSUE TITLE
Shell_Sort

### ISSUE THREAD

**Issue by thejaswin123** [prathimacode-hub/PyAlgo-Tree#71]
---
Title: Shell Sort
About: Shell sort python program 
Name: Thejaswin S
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Its a new Feature.

**Describe the solution you'd like...**

I would like to add the program to sort numbers using Shell sort in min time complexity and space complexity.

**Approach to be followed (optional):**

language to be used is python and comments will be added to code.

**Comment by prathimacode-hub** [comment]
Issue assigned. @thejaswin123
