### ISSUE TITLE
Segment tree creation

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#72]
---
Title: Segment tree creation
About: Aim is to create project to create a segment tree based on a given array
Name: Pushpit Jain
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

Segment tree are an efficient way of preprocessing the array, where all array elements are leaf nodes, and the internal nodes store some processed data. These can decrease time complexity of the range sum queries or any other operations and thus is very commonly used. 

**Describe the solution you'd like...**
I will use the python lists to store the values and use an iterative approach to create the segment tree

Please assign me this issue under Devincept21

**Comment by prathimacode-hub** [comment]
Issue assigned. @pushpit-J19
