### ISSUE TITLE
Doubly Linked List

### ISSUE THREAD

**Issue by nknantha** [prathimacode-hub/PyAlgo-Tree#73]
---
Title: Doubly Linked List
About: Doubly Linked List implementation in Python.
Name: NanthaKumar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] **DevIncept Participant**
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No. I wants to add new feature.

**Describe the solution you'd like...**
A Doubly Linked List is a type of Linked List in which nodes are bi-directionally connected. It consist of operations like add, delete, update, insert. So that we can use this as an alternative of arrays.

**Comment by prathimacode-hub** [comment]
Issue assigned. @nknantha
