### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#8]
---
Title: Selection Sort in python
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
N.A.its a new feature.

**Describe the solution you'd like...**
I would like to add Selection sort solution.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

 through comments,I will explain my approach and add a readme for examples and Output ss

**Comment by siddhi-244** [comment]
I have made a pr for bubble sort. Please assign me this

**Comment by prathimacode-hub** [comment]
This issue doesn't have template. Kindly add that and I shall assign the issue. @siddhi-244

**Comment by siddhi-244** [comment]
> This issue doesn't have template. Kindly add that and I shall assign the issue. @siddhi-244

Done maam

**Comment by prathimacode-hub** [comment]
> > This issue doesn't have template. Kindly add that and I shall assign the issue. @siddhi-244
> 
> Done maam

Few changes needed over the repo. I shall assign this issue. But address the changes, before you work on this. @siddhi-244
