### ISSUE TITLE
Average Calculator

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#81]
---
Title: Average Calculator
About: The aim is to calculate average of all the distinct integers entered by the user.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The average of only unique integers entered by user, will get printed out.

**Describe the solution you'd like...**

Use arrays and sets in python to solve the problem.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
