### ISSUE TITLE
Binary tree to DLL 

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#83]
---
Title: Binary tree to DLL 
About: Aim is to create project to convert a binary tree to a doubly linked list in place following in-order
Name: Pushpit Jain
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

This is called flattening a binary tree used to convert data stored in a tree to a 1d data structure. The challenge is to do it in-place while following the in-order traversal. 

**Describe the solution you'd like...**
I will use the python class to create a nodes for the binary tree / dll, and the left and right pointers in nodes are to be used as previous and next pointers in converted DLL.

Please assign me this issue under Devincept21

**Comment by prathimacode-hub** [comment]
Issue assigned. @pushpit-J19
