### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by RC2208** [prathimacode-hub/PyAlgo-Tree#84]
Title: Insertion Sort
About: Write python code on insertion sort
Name: Ritika Chand
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

 Sorting an array.

**Describe the solution you'd like...**
Making a code for insertion sort and counting no. of swaps and comparisons that are made.

**Comment by prathimacode-hub** [comment]
Issue assigned. @RC2208
