### ISSUE TITLE
Tuples

### ISSUE THREAD

**Issue by bhagyashree-06** [prathimacode-hub/PyAlgo-Tree#89]
I want to create a detailed Readme file, explaining tuples, inside the data structures folder

**Comment by bhagyashree-06** [comment]
---
Title: Tuples
About: I want to create a readme file, inside the data structure folder, explaining tuples.
Name: Bhagyashree Pathak
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor




**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.




**Describe the solution you'd like...**


I would like to explain tuples and its functionalities (creating tuple, accessing items, finding items, copying tuples, concatenation etc.)





**Approach to be followed (optional):**
I would like to create a readme file for the same



**Additional context**


Please assign this issue, thanks.

**Comment by prathimacode-hub** [comment]
What about the project? No project? Only explanation? @bhagyashree-06

**Comment by bhagyashree-06** [comment]
yes, as of now, I thought only about the explanation part

**Comment by prathimacode-hub** [comment]
But it doesn't go like that, project file is as well needed along with the explanation. @bhagyashree-06
