### ISSUE TITLE
Bubble_Sort

### ISSUE THREAD

**Issue by siddhi-244** [prathimacode-hub/PyAlgo-Tree#9]
---
Title: Bubble Sort in python
Name: SIDDHI BHANUSHALI 
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
N.A.its a new feature.

**Describe the solution you'd like...**
I would like to add Bubble sort solution.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

I would first give the problem link and then through comments,I will explain my approach

**Comment by prathimacode-hub** [comment]
Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
So let me know of the script you are choosing. 
@siddhi-244

**Comment by siddhi-244** [comment]
> Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
> So let me know of the script you are choosing.
> @siddhi-244

Python

**Comment by siddhi-244** [comment]
@prathimacode-hub  Have a look

**Comment by prathimacode-hub** [comment]
> > Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
> > So let me know of the script you are choosing.
> > @siddhi-244
> 
> Python

Obviously it's python. Follow the issue templaate given. @siddhi-244

**Comment by siddhi-244** [comment]
> > > Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
> > > So let me know of the script you are choosing.
> > > @siddhi-244
> > 
> > 
> > Python
> 
> Obviously it's python. You template lacks details. @siddhi-244

I have updated the comment

**Comment by prathimacode-hub** [comment]
> > > > Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
> > > > So let me know of the script you are choosing.
> > > > @siddhi-244
> > > 
> > > 
> > > Python
> > 
> > 
> > Obviously it's python. You template lacks details. @siddhi-244
> 
> I have updated the comment

Questions are empty. Atleast add a small description in the template on how would you like to proceed. @siddhi-244

**Comment by siddhi-244** [comment]
> > > > > Please follow the issue template given in README to get issue assigned. You can work on only 1 issue at a time
> > > > > So let me know of the script you are choosing.
> > > > > @siddhi-244
> > > > 
> > > > 
> > > > Python
> > > 
> > > 
> > > Obviously it's python. You template lacks details. @siddhi-244
> > 
> > 
> > I have updated the comment
> 
> Questions are empty. Atleast add a small description in the template on how would you like to proceed. @siddhi-244

Done maam

**Comment by prathimacode-hub** [comment]
Ok, see the project structure first before you work so that you know the files you go to add in your project. Issue assigned. @siddhi-244

**Comment by siddhi-244** [comment]
Sure. I read it first before opening issue. I will add this in sorting algorithms

**Comment by siddhi-244** [comment]
Done maam @prathimacode-hub . Really srry for the mistakes next time I will not repeat it
