### ISSUE TITLE
Lowest Common Ancestor Binary Tree

### ISSUE THREAD

**Issue by pushpit-J19** [prathimacode-hub/PyAlgo-Tree#92]
---
Title: Lowest Common Ancestor Binary Tree 
About: Aim is to create project to find lowest common ancestor of 2 nodes in a binary tree
Name: Pushpit Jain
Label: Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

LCA is the first common node, that occurs when we move from 2 nodes to the root. It is a famously asked interview question. It can be translated to many real word and tech world problems.

**Describe the solution you'd like...**
I will use the python class to create a nodes for the binary tree and find the lca using recursive approach.

Please assign me this issue under Devincept21

**Comment by prathimacode-hub** [comment]
Issue assigned. @pushpit-J19
