### ISSUE TITLE
Binary Numbers

### ISSUE THREAD

**Issue by Manasi2001** [prathimacode-hub/PyAlgo-Tree#93]
---
Title: Binary Numbers
About: Given a base-10 integer, n, convert it to binary (base-2). Then find and print the base-10 integer denoting the maximum number of consecutive 1's in n's binary representation.
Name: Manasi Chhibber
Label: Feature Request
Assignee: 'Manasi2001'

---

Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Describe the solution you'd like...**

Instead of using built-in functions, I'll try to code explicitly.

**Comment by prathimacode-hub** [comment]
Issue assigned. @Manasi2001
