### ISSUE TITLE
RSA/EL Gamal cryptosystem

### ISSUE THREAD

**Issue by dilroseR** [prathimacode-hub/PyAlgo-Tree#95]
---
**Title:**  RSA/EL Gamal cryptosystem 

**About:**  Encryption of plaintext using RSA & El-Gamal algorithms, Diffie-Hellman Key Exchange to ensure sender & receiver can only communicate if they have share same secret key

**Name:** Dilrose Reji

**Label:** Feature Request
Assignee: ''

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
- RSA/El-Gamal Algorithm will be implemented using python which helps in encrypting the plaintext to cipher text
- Diffie-Hellman Key exchange algorithm will check if the sender & receiver has the same shared key, if not they can communicate

**Describe the solution you'd like...**
Will be implementing both of them based on the algorithms in python

Kindly assign this to me

**Comment by prathimacode-hub** [comment]
Issue assigned. @dilroseR
