### ISSUE TITLE
Reverse Cipher

### ISSUE THREAD

**Issue by photon149** [prathimacode-hub/PyAlgo-Tree#97]
---
Title: Reverse Cipher
About: Suggest an idea for this project
Name: Shiwansh Raj
Label: Feature Request

---

Define You:

- [x] DevIncept Participant 
- [ ] Contributor

*Is your feature request related to a problem? Please describe.*

I want to create an algorithm for a cryptographic method called as reverse cipher.

*Describe the solution you'd like...*

I would like to use the Reverse Cipher method , in which we input a string from a user and reverse it using the code

*Additional context*

Please assign this to me under Devincept'21

**Comment by prathimacode-hub** [comment]
Issue assigned. @photon149
